#!/bin/bash

# No arg print usage
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <distro>"
fi

# Package installation (unless --no-install is given)
if [ "$2" == "--no-install" ]; then
    echo ">> Skipping package installation as per --no-install flag <<"
else
    # Detect package manager
    pacman --version &> /dev/null
    if [ $? -eq 0 ]; then
        echo ">> Detected pacman package manager. Installing required packages..."
        ./bin/pacman_install
        if [ $? -ne 0 ]; then
            echo "Package installation failed. Exiting."
            exit 1
        fi
    else
        echo "Error: Unsupported package manager."
        exit 1;
    fi
fi

# Lowercase the distro name
DISTRO=$(echo "$1" | tr '[:upper:]' '[:lower:]')
# Make sure disto is supported by checking against folder in current directory
if [ ! -d "$DISTRO" ]; then
    echo "Error: Unsupported distro '$DISTRO'. Supported distros are:"
    ls -d */ | sed 's#/##'
    exit 1
fi

better_stow() {
    $(pwd)/bin/bstow $1 $2
}

echo ">> Installing dotfiles for: $DISTRO <<"

echo ">> STOW distro override  <<"

# Keep track of all the stowed packages
STOWED_PACKAGES=()
for package_dir in "$DISTRO"/*/; do
    package=$(basename "$package_dir")
    echo "\t + $package"
    better_stow $DISTRO $package
    STOWED_PACKAGES+=("$package")
done

echo ">> STOW base <<"

# Stow base packages unless we already did
for base_package_dir in "base"/*/; do
    base_package=$(basename "$base_package_dir")
    if [[ " ${STOWED_PACKAGES[@]} " =~ " ${base_package} " ]]; then
    	echo "\t   $package"
    else
    	echo "\t + $package"
        better_stow base $base_package
    fi
done
