#!/bin/bash

# No arg print usage
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <distro>"
fi

# Package installation (unless --no-install is given)
if [ "$2" == "--no-install" ]; then
    echo ">> Skipping package installation as per --no-install flag <<"
else
    # Detect package manager
    pacman --version &> /dev/null # Pacman
    if [ $? -eq 0 ]; then
        echo ">> Detected pacman package manager. Installing required packages..."
        ./bin/pacman_install
        if [ $? -ne 0 ]; then
            echo "Package installation failed. Exiting."
            exit 1
        fi
    fi
    dnf --version &> /dev/null # DNF
    if [ $? -eq 0 ]; then
        echo ">> Detected dnf package manager. Installing required packages..."
        ./bin/dnf_install
        if [ $? -ne 0 ]; then
            echo "Package installation failed. Exiting."
            exit 1
        fi
    else
        echo "Error: Unsupported package manager."
        exit 1;
    fi
fi

if [ "$2" == "--no-stow" ] || [ "$2" == "--no-link" ]; then
    echo ">> Skipping dotfiles stowing as per --no-stow/--no-link flag <<"
else
    # Lowercase the distro name
    DISTRO=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    # Make sure disto is supported by checking against folder in current directory
    if [ ! -d "$DISTRO" ]; then
        echo "Error: Unsupported distro '$DISTRO'. Supported distros are:"
        ls -d */ | sed 's#/##'
        exit 1
    fi

    better_stow() {
        $(pwd)/bin/bstow $1 $2
    }

    echo ">> Installing dotfiles for: $DISTRO <<"

    echo ">> STOW distro override  <<"

    # Keep track of all the stowed packages
    STOWED_PACKAGES=()
    for package_dir in "$DISTRO"/*/; do
        package=$(basename "$package_dir")
        echo "  + $package"
        better_stow $DISTRO $package
        STOWED_PACKAGES+=("$package")
    done

    echo ">> STOW base <<"

    # Stow base packages unless we already did
    for base_package_dir in "base"/*/; do
        base_package=$(basename "$base_package_dir")
        if [[ " ${STOWED_PACKAGES[@]} " =~ " ${base_package} " ]]; then
            echo "    $base_package (skipped, already stowed)"
        else
            echo "  + $base_package"
            better_stow base $base_package
        fi
    done
fi

# Make fish default shell
if [ "$SHELL" != "$(which fish)" ]; then
    echo ">> Changing default shell to Fish <<"
    chsh -s $(which fish)
fi

echo "___________________________________________________"
echo ">> Some changes require a reboot to take effect. <<"
echo "---------------------------------------------------"

# TODO [hcabel 2026-01-04]: Install firefox default extensions and settings
# TODO [hcabel 2026-01-04]: Install SSH and GPG keys from secure storage
