# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(00010E)
$foreground = rgb(EDF7E8)
$color0 = rgb(000512)
$color1 = rgb(12395B)
$color2 = rgb(A45F3D)
$color3 = rgb(467C6E)
$color4 = rgb(9A8661)
$color5 = rgb(B2A48B)
$color6 = rgb(98AD8E)
$color7 = rgb(DDEBD6)
$color8 = rgb(9AA496)
$color9 = rgb(184C79)
$color10 = rgb(DB7E52)
$color11 = rgb(5EA693)
$color12 = rgb(CDB282)
$color13 = rgb(EDDAB9)
$color14 = rgb(CBE7BE)
$color15 = rgb(DDEBD6)
